#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "jcf/cli"

cli = Dry::CLI.new(JCF::CLI)
begin
  cli.call
rescue JCF::CLI::NotLoggedInError => e
  $stderr.puts "You are not logged in to Cloud Foundry. Please log in and try again."
  $stderr.puts e.message
rescue JCF::CLI::InvalidOptionError => e
  $stderr.puts "You need to supply options. Use --help to get details."
  $stderr.puts e.message
rescue NoMethodError => e
  $stderr.puts "Unexpected error. Please report this."
  $stderr.puts
  $stderr.puts e.message
  $stderr.puts e.backtrace
end
